# Generated by Django 5.0.7 on 2024-10-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0002_initial"),
        ("Teacher", "0005_remove_lunchmenu_timetable_alter_timetable_class_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Teacher.teacher",
            ),
            preserve_default=False,
        ),
    ]
