# Generated by Django 5.0.7 on 2024-10-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0002_class"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Class",
        ),
    ]
