# Generated by Django 5.0.7 on 2024-10-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0003_leave_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Parent.parent",
            ),
        ),
    ]
