# Generated by Django 5.0.7 on 2024-10-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0004_alter_leave_parent"),
        ("Parent", "0004_remove_writemsg_teacher"),
    ]

    operations = []
