# Generated by Django 5.0.7 on 2024-10-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0004_leave"),
        ("Teacher", "0004_remove_teacher_class_id_class_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Teacher.teacher",
            ),
        ),
    ]
