# Generated by Django 5.0.7 on 2024-10-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0005_alter_leave_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="teacher",
        ),
    ]
