# Generated by Django 5.0.7 on 2024-10-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0005_alter_leave_teacher"),
        ("Student", "0002_student_class_id"),
        ("Teacher", "0004_remove_teacher_class_id_class_teacher_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Write_msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_msg", models.TextField(verbose_name="Message Text")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Parent.parent",
                        verbose_name="Sender Parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Student.student",
                        verbose_name="Student Involved",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Teacher.teacher",
                        verbose_name="Recipient Teacher",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Leave",
        ),
    ]
