# Generated by Django 5.0.7 on 2024-10-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0006_write_msg_delete_leave"),
        ("Student", "0002_student_class_id"),
        ("Teacher", "0004_remove_teacher_class_id_class_teacher_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("SICK", "Sick Leave"),
                            ("CASUAL", "Casual Leave"),
                            ("EMERGENCY", "Emergency Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("leave_description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Parent.parent"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WriteMsg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_msg", models.TextField(verbose_name="Message Text")),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Teacher Response"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Parent.parent",
                        verbose_name="Sender Parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Student.student",
                        verbose_name="Student Involved",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Teacher.teacher",
                        verbose_name="Recipient Teacher",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Write_msg",
        ),
    ]
