# Generated by Django 5.0.7 on 2024-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0006_write_msg_delete_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="write_msg",
            name="response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Teacher Response"
            ),
        ),
    ]
