# Generated by Django 5.0.7 on 2024-10-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0006_merge_20241014_1234"),
        ("Parent", "0006_merge_20241014_1430"),
    ]

    operations = []
