# Generated by Django 5.0.7 on 2024-10-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Parent", "0007_merge_20241014_1939"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="teacher",
        ),
    ]
