# Generated by Django 5.0.7 on 2024-10-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0002_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="class_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Teacher.class",
            ),
        ),
    ]
