# Generated by Django 5.0.7 on 2024-10-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0003_rename_week_lunchmenu_week_end_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("teacher", "class_id")},
        ),
    ]
