# Generated by Django 5.0.7 on 2024-10-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0003_teacher_class_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="class_id",
        ),
        migrations.AddField(
            model_name="class",
            name="teacher_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Teacher.teacher",
            ),
        ),
    ]
