# Generated by Django 5.0.7 on 2024-10-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0004_alter_timetable_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lunchmenu",
            name="timetable",
        ),
        migrations.AlterField(
            model_name="timetable",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="Teacher.class"
            ),
        ),
    ]
