# Generated by Django 5.0.7 on 2024-10-11 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
        ("Teacher", "0006_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="Student.student",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="is_present",
            field=models.BooleanField(default=True),
        ),
    ]
