# Generated by Django 5.0.7 on 2024-10-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
        ("Teacher", "0007_attendance_student_alter_attendance_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
    ]
