# Generated by Django 5.0.7 on 2024-10-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
        ("Teacher", "0007_attendance_student_alter_attendance_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="")),
                ("announcement", models.TextField(verbose_name="")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Teacher.teacher",
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
