# Generated by Django 5.0.7 on 2024-10-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
        ("Teacher", "0009_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
    ]
