# Generated by Django 5.0.7 on 2024-10-12 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0011_remove_announcement_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="announcement",
            name="announcement",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
