# Generated by Django 5.0.7 on 2024-10-12 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0013_alter_announcement_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
