# Generated by Django 5.0.7 on 2024-10-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0008_alter_attendance_unique_together"),
        ("Teacher", "0014_alter_announcement_date"),
    ]

    operations = []
