# Generated by Django 5.0.7 on 2024-10-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0015_merge_20241014_1214"),
        ("Teacher", "0015_merge_20241014_1215"),
    ]

    operations = []
