# Generated by Django 5.0.7 on 2024-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0016_merge_20241014_1234"),
        ("Teacher", "0016_merge_20241014_1430"),
    ]

    operations = []
