# Generated by Django 5.0.7 on 2024-10-01 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
        ("Teacher", "0003_teacher_class_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Teacher.class",
            ),
        ),
    ]
